### ISSUE TITLE
Определиться с лицензией

### ISSUE THREAD

**Issue by dmpas** [leoniv/v8unpack#2]
Мы сейчас собираем пакеты для linux-систем и от нас требуется указание лицензии. Есть ли возможность связаться с автором и прояснить этот вопрос?

**Comment by leoniv** [comment]
Я с автором не знаком ссылок на лицензии не находил. Поищите его на инфостате

-----Исходное сообщение-----
От: "Sergey Batanov" notifications@github.com
Отправлено: ‎22.‎07.‎2015 14:42
Кому: "leoniv/v8unpack" v8unpack@noreply.github.com
Тема: [v8unpack] Определиться с лицензией (#2)

Мы сейчас собираем пакеты для linux-систем и от нас требуется указание лицензии. Есть ли возможность связаться с автором и прояснить этот вопрос?

**Comment by dmpas** [comment]
Понял, спасибо.
